import { UserProfile } from './user-profile';
import { UserRole } from '../../../shared/types/user-roles';

const mockUsers: UserProfile[] = [
    {
        id: 'a7b8c9d0e1f2',
        role: UserRole.Admin,
        firstName: 'Анна',
        lastName: 'Ковальчук',
        nickName: 'АннаК',
        avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
        mobilePhone: '380671234567',
        email: 'anna@gmail.com',
        city: 'Київ',
        address: 'Вул. Антоновича, 45, кв. 112',
    },
    {
        id: 'f3e4d5c6b7a8',
        role: UserRole.Operator,
        firstName: 'Віталій',
        lastName: 'Шевченко',
        nickName: 'ВіталікШ',
        avatar: 'https://randomuser.me/api/portraits/men/34.jpg',
        mobilePhone: '380998765432',
        email: 'vitaliy@gmail.com',
        city: 'Львів',
        address: 'Просп. Миру, 88, кв. 7',
    },
    {
        id: 'b2c3d4e5f6a7',
        role: UserRole.Operator,
        firstName: 'Софія',
        lastName: 'Ткаченко',
        nickName: 'СофіяТ',
        avatar: 'https://randomuser.me/api/portraits/women/42.jpg',
        mobilePhone: '380631122334',
        email: 'sofia@gmail.com',
        city: 'Одеса',
        address: 'Вул. Успенська, 20',
    },
    {
        id: 'd9e0f1a2b3c4',
        role: UserRole.Guest,
        firstName: 'Максим',
        lastName: 'Григоренко',
        avatar: 'https://randomuser.me/api/portraits/men/77.jpg',
        mobilePhone: '380509876543',
        email: 'maksym@gmail.com',
        city: 'Харків',
        address: 'Вул. Сумська, 5',
    },
    {
        id: 'g1h2i3j4k5l6',
        role: UserRole.Guest,
        firstName: 'Олег',
        lastName: 'Мельничук',
        avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
        mobilePhone: '380962345678',
        email: 'oleg@gmail.com',
        city: 'Рівне',
        address: 'Вул. Соборна, 15, кв. 3',
    },
    {
        id: 'm7n8o9p0q1r2',
        role: UserRole.Guest,
        firstName: 'Юлія',
        lastName: 'Поліщук',
        nickName: 'ЮляП',
        avatar: 'https://randomuser.me/api/portraits/women/29.jpg',
        mobilePhone: '380934567890',
        email: 'yulia@mail.com',
        city: 'Івано-Франківськ',
        address: 'Вул. Незалежності, 100Б',
    },
    {
        id: 's3t4u5v6w7x8',
        role: UserRole.Admin,
        firstName: 'Андрій',
        lastName: 'Лисенко',
        nickName: 'ЕндрюЛ',
        avatar: 'https://randomuser.me/api/portraits/men/91.jpg',
        mobilePhone: '380665432109',
        email: 'andrii@gmail.com',
        city: 'Київ',
        address: 'Вул. Жилянська, 90',
    },
];

export default mockUsers;
